#pragma once

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)

// Device configuration
#define CFG_TUD_ENDPOINT0_SIZE 64

// Enable USB-MIDI
#define CFG_TUD_MIDI 1
#define CFG_TUD_MIDI_EP_BUFSIZE 64